# fly.toml file generated for NexLinkFly app

app = "nexlinkfly"
primary_region = "lhr"

[build]
  # On utilise Docker pour construire l'image
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  CHRIS_API_KEY="NexLinkKey"
  SHOPIFY_APP_URL="https://nexlinkfly.fly.dev"
  SHOPIFY_API_KEY="NexLinkKey"
  SHOPIFY_API_SECRET="NexLinkSecret"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = 10000
    restart_limit = 0
