app = "nexlinkfly"

[env]
NODE_ENV = "production"
PORT = "3000"
CHRIS_API_KEY = "NexLinkKey"
SHOPIFY_APP_URL = "https://nexlinkfly.fly.dev"
SHOPIFY_API_KEY = "80b31d1514b7c9125368654632ad21ff"
SHOPIFY_API_SECRET = "4a4f8132501fe1d82d69c4eb99b55eca"
SCOPES = "read_all_orders,read_checkout_branding_settings,read_customers,read_orders,write_customers,write_orders"

[build]
  dockerfile = "Dockerfile"

[[services]]
internal_port = 3000
protocol = "tcp"

  [services.concurrency]
  type = "connections"
  soft_limit = 25
  hard_limit = 50

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

  [services.http_checks]
  interval = "10s"
  timeout = "2s"
  grace_period = "30s"
  method = "get"
  path = "/"
