# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "80b31d1514b7c9125368654632ad21ff"
name = "Sendup Whatsapp Abandoned Cart"
handle = "nexlink"
application_url = "https://nexlinkfly.fly.dev"
embedded = true

[build]
# En dev, les URL sont mises à jour automatiquement
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "https://nexlinkfly.fly.dev/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "https://nexlinkfly.fly.dev/webhooks/app/uninstalled"

[access_scopes]
# Déclare uniquement les scopes que tu utilises
scopes = "read_customers,read_orders,read_products"

[auth]
redirect_urls = [
  "https://nexlinkfly.fly.dev/auth/callback",
  "https://nexlinkfly.fly.dev/auth/shopify/callback"
]

[pos]
embedded = false

[app_preferences]
url = "https://nexlinkfly.fly.dev/preferences"
